{% set name = "pyshortcuts" %}
{% set version = "1.9.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyshortcuts-{{ version }}.tar.gz
  sha256: ab5c12c16277882b282bc07fe085237002ec787f3c043a4ac5c46a6cd3dbde26

build:
  number: 0
  entry_points:
    - pyshortcut = pyshortcuts:shortcut_cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - charset-normalizer
    - pywin32  # [win]

test:
  imports:
    - pyshortcuts
  commands:
    - pip check
    - pyshortcut --help
  requires:
    - pip

about:
  home: http://github.com/newville/pyshortcuts
  summary: create desktop and Start Menu shortcuts for python scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
